language: python
python:
  - 3.6
  - 3.7
install:
  - sudo apt-get -y update
  - sudo apt-get -y install build-essential
  - sudo apt-get -y install samtools
  - sudo apt-get -y install rna-star
  - pip install nose
  - pip install codecov
  - pip install pysam==0.15.3
  - python setup.py install
script:
  - wget https://ftp-trace.ncbi.nlm.nih.gov/sra/sdk/2.10.4/setup-apt.sh
  - chmod 755 setup-apt.sh
  - sudo ./setup-apt.sh
  - source /etc/profile.d/sra-tools.sh
  - git clone https://github.com/marianogabitto/ChromA.git
  - cd ChromA
  - python setup.py install
  - cd ..
  - python -c "import os; print(repr(os.name))"
  - coverage run --source=srrTomat0 setup.py test
after_success:
  - codecov
after_failure:
  - pwd
  - find .
