language: python
python:
  - 3.6
  - 3.7
install:
  - sudo apt-get -y update
  - sudo apt-get -y install samtools
  - sudo apt-get -y install sra-toolkit
  - sudo apt-get -y install rna-star
  - pip install nose
  - pip install codecov
  - python setup.py install
script:
  - git clone https://github.com/marianogabitto/ChromA.git
  - python ChromA/setup.py install
  - rm -r ChromA
  - python -c "import os; print(repr(os.name))"
  - coverage run --source=srrTomat0 setup.py test
after_success:
  - codecov
after_failure:
  - pwd
  - find .
